### ISSUE TITLE
Other compile command needed

### ISSUE THREAD

**Issue by Soily** [AlexViaColl/alsa-playback#1]
Hello,

i just tried this example on my linux-PC and on an embedded target, and I needed to use this command:
on PC:
g++ -Wall -std=c11 -pedantic -o playback main.c -lasound 
gcc was not working.

on embedded Target:
${CXX} ${LDFLAGS} ${S}/main.c -oloop-sound -lasound -I{WORKDIR}

Do you know why it's not working with your command you specified in build.sh?

**Comment by AlexViaColl** [comment]
Hi, can you please provide more information on the compile error you are getting on the embedded platform? What version of gcc did you use?

**Comment by Soily** [comment]
Hello Alex,

when I'm executing your build.sh on my Ubuntu Host (22.04) as it is, right now I got the following errors:

ubuntu_paddy@paddylinux:~/Development/alsa-dev/alsa-playback$ ./build.sh 

/usr/bin/ld: /tmp/ccM91Keg.o: in function `check':

main.c:(.text+0x1b): undefined reference to `snd_strerror'

/usr/bin/ld: /tmp/ccM91Keg.o: in function `square_wave':

main.c:(.text+0xc9): undefined reference to `floorf'

/usr/bin/ld: main.c:(.text+0xf2): undefined reference to `floorf'

/usr/bin/ld: /tmp/ccM91Keg.o: in function `sine_wave':

main.c:(.text+0x1cd): undefined reference to `sinf'

/usr/bin/ld: /tmp/ccM91Keg.o: in function `main':

main.c:(.text+0xa35): undefined reference to `snd_pcm_open'

/usr/bin/ld: main.c:(.text+0xa41): undefined reference to `snd_pcm_hw_params_sizeof'

/usr/bin/ld: main.c:(.text+0xace): undefined reference to `snd_pcm_hw_params_sizeof'

/usr/bin/ld: main.c:(.text+0xafe): undefined reference to `snd_pcm_hw_params_any'

/usr/bin/ld: main.c:(.text+0xb23): undefined reference to `snd_pcm_hw_params_set_access'

/usr/bin/ld: main.c:(.text+0xb48): undefined reference to `snd_pcm_hw_params_set_format'

/usr/bin/ld: main.c:(.text+0xb6d): undefined reference to `snd_pcm_hw_params_set_channels'

/usr/bin/ld: main.c:(.text+0xb94): undefined reference to `snd_pcm_hw_params_set_rate'

/usr/bin/ld: main.c:(.text+0xbbb): undefined reference to `snd_pcm_hw_params_set_periods'

/usr/bin/ld: main.c:(.text+0xbe2): undefined reference to `snd_pcm_hw_params_set_period_time'

/usr/bin/ld: main.c:(.text+0xc02): undefined reference to `snd_pcm_hw_params'

/usr/bin/ld: main.c:(.text+0xce9): undefined reference to `snd_pcm_writei'

/usr/bin/ld: main.c:(.text+0xd4a): undefined reference to `snd_pcm_writei'

/usr/bin/ld: main.c:(.text+0xf5c): undefined reference to `snd_pcm_writei'

/usr/bin/ld: main.c:(.text+0xfa4): undefined reference to `snd_pcm_drain'

/usr/bin/ld: main.c:(.text+0xfba): undefined reference to `snd_pcm_close'

collect2: error: ld returned 1 exit status

As GCC I use:

gcc --version

gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

**Comment by Soily** [comment]
Hi again,
I just found a command which worked for me for building on my linux host and using the GCC instead of g++ compiler.

gcc -Wall -Werror -std=c11 -pedantic -o playback main.c -lasound -lm
will do the trick.

Looks like that the option -lm must be the last in the command.

I will mark  this issue now as closed. Thanks a lot.

Kind Regards
Paddy

**Comment by Soily** [comment]
Btw.

The song skyhigh sounds like, you could also like my electronic music productions.
You can find them over the links:
https://www.freethinkers-inc.de
https://soundcloud.com/freethinkers-inc

Have a great time.
Paddy

**Comment by AlexViaColl** [comment]
Hi, I'm glad you managed to resolve the issue.

Looks like you were missing [pkg-config](https://www.freedesktop.org/wiki/Software/pkg-config/) which is used to resolve the library names (`-lasound` in this case). I have added a dependencies section in the [README](https://github.com/AlexViaColl/alsa-playback/blob/main/README.md) to point that out, and also enabled tracing in [build.sh](https://github.com/AlexViaColl/alsa-playback/blob/main/build.sh) to troubleshoot similar issues more easily.

I'll make sure to check out your productions and thank you for the feedback!

**Comment by seamusdemora** [comment]
> Looks like you were missing [pkg-config](https://www.freedesktop.org/wiki/Software/pkg-config/) which ...

Don't know about @Soily , but I do have `pkg-config` on my system... maybe you should update yr `build.sh`??

**Comment by Soily** [comment]
> > Looks like you were missing [pkg-config](https://www.freedesktop.org/wiki/Software/pkg-config/) which ...
> 
> Don't know about @Soily , but I do have `pkg-config` on my system... maybe you should update yr `build.sh`??

No I don't use pkg-config. For me the application was building and running fine after what I did what I described above. The issue you have shown a couple of hours ago, doesn't come from the application itself, but might be related to how you use the alsa library. Please check your application code and have a look into the source code of the alsa library.

**Comment by seamusdemora** [comment]
@Soily : 
Thanks for the suggestion... I have no "application code"; I'm simply trying to run the example posted in this repo. 

As for having a look at the alsa library...  well, I'd probably have more luck consulting a "crystal ball". LOL

Anyway - seems @AlexViaColl is indisposed or lost interest in this. I've been using `bluez-alsa` & having mostly good results. I thought I'd try this hoping to learn more about the innards of alsa, but maybe not... 
Thanks again for your comment!
